import type { TourConfig } from "@/features/learning/types";
import { getModule } from "@/shared/lib/curriculum";
import { openModal } from "@/shared/lib/tour-utils";

const HOME = "/";
const mod = getModule("oms")!;

export const OmsTour: TourConfig = {
  moduleId: "oms",
  pageKey: "oms",
  pageHref: "/oms/fulfillment-locations",
  parentModuleName: "Fulfillment Locations",
  track: "OMS",
  number: mod.number,
  title: mod.title,
  skills: mod.skills,
  homeHref: HOME,
  glossaryKeys: ["Fulfillment Location", "Location Type", "Category"],
  pitfalls: [
    "Forgetting Refresh after changing filters",
    "Wrong Location Type (Store vs Warehouse)",
    "Leaving Timezone blank",
    "Creating a location without an approved request",
  ],
  scenarios: [
    {
      id: "onboard",
      title: "Find then add",
      story: "Confirm warehouse kisah exists, then add Demo Central Warehouse in Bengaluru.",
    },
  ],
  summary: {
    title: "Fulfillment Locations — complete",
    intro: "You filtered the directory and registered a new location.",
    takeaways: ["Filter → Refresh → Find", "Use Location ID in tickets", "Set Type and Timezone carefully", "Country before State"],
    recap: ["Find empty? Clear filters and Refresh", "Ask OMS Config if Type is unclear", "Capture Location ID after Submit"],
  },
  quiz: [
    {
      question: "After changing filters you should…",
      choices: ["Refresh", "Exit", "Add Location", "Ignore"],
      answer: 0,
      explain: "Refresh applies filters.",
    },
    {
      question: "Which field drives SLA / cutoffs?",
      choices: ["Area", "Timezone", "Address Line 2", "Contact Number"],
      answer: 1,
      explain: "Timezone drives timers.",
    },
    {
      question: "State list empty — fix by…",
      choices: ["Selecting Country first", "Restarting PC", "Clearing Name", "Picking USP"],
      answer: 0,
      explain: "State depends on Country.",
    },
  ],
  steps: [
    {
      element: "#oms-location-type",
      title: "Location Type",
      description: "Optional filter. Example: <strong>WAREHOUSE</strong>",
      practicePrompt: "WAREHOUSE",
      expected: { type: "select", selector: "#oms-location-type", value: "WAREHOUSE" },
      skillLabel: "Browse",
      skillIndex: 1,
    },
    {
      element: "#oms-category",
      title: "Category",
      description: "Optional filter. Example: <strong>PRIMARY</strong>",
      practicePrompt: "PRIMARY",
      expected: { type: "select", selector: "#oms-category", value: "PRIMARY" },
      skillLabel: "Browse",
      skillIndex: 1,
    },
    {
      element: "#oms-btn-refresh",
      title: "Refresh",
      description: "Apply filters.",
      expected: { type: "action" },
      skillLabel: "Browse",
      skillIndex: 1,
    },
    {
      element: "#oms-find-results",
      title: "Find",
      description: "Optional. Example: <strong>kisah</strong>",
      practicePrompt: "kisah",
      expected: { type: "input", selector: "#oms-find-results", value: "kisah" },
      skillLabel: "Browse",
      skillIndex: 2,
    },
    {
      element: "#oms-results-table",
      title: "Directory",
      description: "Review Location ID, contact, address.",
      expected: { type: "action" },
      side: "top",
      skillLabel: "Browse",
      skillIndex: 2,
    },
    {
      element: "#oms-btn-add",
      title: "Add New Location",
      description: "Open the create form. Click <strong>Next</strong> to continue inside the dialog.",
      expected: { type: "action" },
      openModalOnNext: "modal-add-location",
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "#oms-location-name",
      title: "Name *",
      description: "Required. <strong>Demo Central Warehouse</strong>",
      practicePrompt: "Demo Central Warehouse",
      required: true,
      expected: { type: "input", selector: "#oms-location-name", value: "Demo Central Warehouse" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "input[name='oms-loc-type']",
      title: "Type *",
      description: "Required. Select <strong>Warehouse</strong>.",
      practicePrompt: "Warehouse",
      required: true,
      expected: { type: "radio", name: "oms-loc-type", value: "Warehouse" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "#oms-contact-name",
      title: "Contact Name *",
      description: "Required. <strong>John Doe</strong>",
      practicePrompt: "John Doe",
      required: true,
      expected: { type: "input", selector: "#oms-contact-name", value: "John Doe" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "#oms-contact-email",
      title: "Email",
      description: "Optional. Example: <strong>john.doe@example.com</strong>",
      practicePrompt: "john.doe@example.com",
      expected: { type: "input", selector: "#oms-contact-email", value: "john.doe@example.com" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "#oms-contact-number",
      title: "Phone",
      description: "Optional. Example: <strong>9876543210</strong>",
      practicePrompt: "9876543210",
      expected: { type: "input", selector: "#oms-contact-number", value: "9876543210" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 3,
    },
    {
      element: "#oms-address1",
      title: "Address *",
      description: "Required. <strong>Plot 42, Industrial Area Phase 2</strong>",
      practicePrompt: "Plot 42, Industrial Area Phase 2",
      required: true,
      expected: { type: "input", selector: "#oms-address1", value: "Plot 42, Industrial Area Phase 2" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
    {
      element: "#oms-city",
      title: "City *",
      description: "Required. <strong>Bengaluru</strong>",
      practicePrompt: "Bengaluru",
      required: true,
      expected: { type: "input", selector: "#oms-city", value: "Bengaluru" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
    {
      element: "#oms-pincode",
      title: "Pincode *",
      description: "Required. <strong>560066</strong>",
      practicePrompt: "560066",
      required: true,
      expected: { type: "input", selector: "#oms-pincode", value: "560066" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
    {
      element: "#oms-country",
      title: "Country *",
      description: "Required. <strong>India</strong>",
      practicePrompt: "India",
      required: true,
      expected: { type: "select", selector: "#oms-country", value: "IN" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
    {
      element: "#oms-state",
      title: "State *",
      description: "Required. <strong>Karnataka</strong>",
      practicePrompt: "Karnataka",
      required: true,
      expected: { type: "select", selector: "#oms-state", value: "KA" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
    {
      element: "#oms-location-tz",
      title: "Timezone *",
      description: "Required. <strong>IST</strong>",
      practicePrompt: "IST",
      required: true,
      expected: { type: "select", selector: "#oms-location-tz", value: "IST" },
      onEnter: () => openModal("modal-add-location"),
      skillLabel: "Add",
      skillIndex: 4,
    },
  ],
};
